FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
LABEL version="0.2"
WORKDIR /src
COPY ./src/server/TextStreams.Migrations .
RUN     dotnet restore ./TextStreams.Migrations.csproj && \
        dotnet publish ./TextStreams.Migrations.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /src
COPY --from=build-env /src/out .
ENTRYPOINT ["dotnet", "TextStreams.Migrations.dll"]